databases.work.datasources.jdbc.sqlserver.DATABASEURI=jdbc\:sqlserver\://denodo-db-sqlserver\:1433;databaseName\=denodo
databases.work.datasources.jdbc.sqlserver.USERNAME=sa
databases.work.datasources.jdbc.sqlserver.USERPASSWORD=MksQnuvtuLJdwTIP8ieyuXPyAUJzdfPCIQ24lWqnCDyFK8idbJ16ctB2le6koiwOvS0hpXUukXGJJFXyjZMn6Gq24Q/F2DGaqPTg7v6e3ipQHl2LlqJZjiZIn0u623kc6NtIEH2C/DITZogs3UsRmA\=\=
databases.work.datasources.jdbc.sqlserver.USERPASSWORD.ENCRYPTED=ENCRYPTED
