databases.work1.datasources.jdbc.sqlserver.DATABASEURI=jdbc\:sqlserver\://denodo-db-sqlserver\:1433;databaseName\=denodo
databases.work1.datasources.jdbc.sqlserver.USERNAME=sa
databases.work1.datasources.jdbc.sqlserver.USERPASSWORD=CJF5H5BPdjhEjDLTtzAhvCIcvkPhjKIceP1yrrsTq2jgR4bwSatNU0d9QR7GFzUL1copDKNqcbCue93zyg8OsFnfmssJuAoPeT5CW+QToFyTzgKSQNheaScy/PLSUhNZe6YAqD4zornfOs+7TtiEMQ\=\=
databases.work1.datasources.jdbc.sqlserver.USERPASSWORD.ENCRYPTED=ENCRYPTED
